package com.sangusantri.app.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/** One local reading-activity event (QUR-FR-017), written only after the position advances by at
 * least one ayat — mirrors `AmaliyahCompletionEventEntity`'s autogenerated-id snapshot-log shape. */
@Entity(tableName = "quran_reading_sessions")
data class QuranReadingSessionEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val surahNumber: Int,
    val startAyat: Int,
    val endAyat: Int,
    val readAtEpochMillis: Long,
)
